export const siteConfig = {
  name: "Rivorn - Luxury Watches",
  tagline: "Luxury on your wrist. Watches designed for your lifestyle.",
  baseUrl: "https://www.oussaura.com",
  phone: "+213 798 70 04 47",
  phone2: "+213 798 70 04 47",
  phone3: "+213 798 70 04 47",
  email: "contact@rivorn.com",
  address: "Alger, Algerie",
  googleMapsLink: "https://maps.app.goo.gl/nh5JsSvQrQiXgHSj7",
  whatsappLink: "https://wa.me/213798700447",
  instagramLink: "https://www.instagram.com/dna__watches/",
  facebookLink: "https://www.facebook.com/dz.vente.tt",
  tiktokLink: "https://www.tiktok.com/@oussaura.boutique",
  description:
    "Rivorn - Luxury Watches offers original watches, jewelry and premium accessories with delivery to all 58 wilayas and cash on delivery.",
  keywords: [
    "Rivorn",
    "luxury watches",
    "montres Algerie",
    "bijoux Algerie",
    "montres originales",
    "magasin de montres",
    "livraison 58 wilayas",
  ],
};
